name: Build and Push

on:
  repository_dispatch: # Repo dispatch from voicecraft repo..., automated
    types: [voicecraft-new-release]
  workflow_dispatch: # click the button on Github repo!

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Get latest VoiceCraft version
        id: voicecraft
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: SineVector241/VoiceCraft-MCBE_Proximity_Chat
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Get latest VoiceCraft_Docker Image Version
      #  id: latest
      #  uses: shrink/actions-docker-latest-image@v1
      #  with:
      #    repository: docker.pkg.github.com/${{ github.repository }}/voicecraft

      #- name: Exit if this latest version is the latest VoiceCraft version
      #  if: ${{ steps.latest.outputs.tag == steps.voicecraft.outputs.release }}
      #  run: exit 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/voicecraft:latest
            ${{ vars.DOCKERHUB_USERNAME }}/voicecraft:${{ steps.voicecraft.outputs.release }}
            ghcr.io/${{ github.repository_owner }}/voicecraft:latest
            ghcr.io/${{ github.repository_owner }}/voicecraft:${{ steps.voicecraft.outputs.release }}
